import { Account, Contact } from "./types";

export const mockContacts: Contact[] = [
  // Executive Leadership
  {
    id: "1",
    name: "Robert Morrison",
    title: "CEO",
    department: "Executive",
    seniority: "executive",
    email: "robert.morrison@acmecorp.com",
    phone: "+1 (555) 100-0001",
    status: "champion",
    engagementScore: 98,
    role: "economic-buyer",
    linkedIn: "https://linkedin.com/in/robertmorrison",
    contactOwner: "Sarah Williams",
    lastContact: "2025-01-22",
  },
  {
    id: "2",
    name: "Jennifer Liu",
    title: "CFO",
    department: "Executive",
    seniority: "executive",
    email: "jennifer.liu@acmecorp.com",
    phone: "+1 (555) 100-0002",
    status: "engaged",
    engagementScore: 85,
    role: "economic-buyer",
    reportsTo: "1",
    linkedIn: "https://linkedin.com/in/jenniferliu",
    contactOwner: "Sarah Williams",
    lastContact: "2025-01-20",
  },
  {
    id: "3",
    name: "Marcus Thompson",
    title: "COO",
    department: "Executive",
    seniority: "executive",
    email: "marcus.thompson@acmecorp.com",
    phone: "+1 (555) 100-0003",
    status: "warm",
    engagementScore: 75,
    role: "influencer",
    reportsTo: "1",
    linkedIn: "https://linkedin.com/in/marcusthompson",
    contactOwner: "Michael Chen",
    lastContact: "2025-01-18",
  },
  {
    id: "4",
    name: "Sarah Chen",
    title: "CTO",
    department: "Executive",
    seniority: "executive",
    email: "sarah.chen@acmecorp.com",
    phone: "+1 (555) 100-0004",
    status: "champion",
    engagementScore: 95,
    role: "champion",
    reportsTo: "1",
    linkedIn: "https://linkedin.com/in/sarahchen",
    contactOwner: "Michael Chen",
    lastContact: "2025-01-23",
  },
  {
    id: "5",
    name: "David Rodriguez",
    title: "CMO",
    department: "Executive",
    seniority: "executive",
    email: "david.rodriguez@acmecorp.com",
    phone: "+1 (555) 100-0005",
    status: "engaged",
    engagementScore: 82,
    role: "influencer",
    reportsTo: "1",
    linkedIn: "https://linkedin.com/in/davidrodriguez",
    contactOwner: "Sarah Williams",
    lastContact: "2025-01-21",
  },

  // IT Department
  {
    id: "6",
    name: "Rachel Kim",
    title: "Head of Engineering",
    department: "Technology",
    seniority: "director",
    email: "rachel.kim@acmecorp.com",
    phone: "+1 (555) 200-0001",
    status: "engaged",
    engagementScore: 88,
    role: "technical-evaluator",
    reportsTo: "4",
    linkedIn: "https://linkedin.com/in/rachelkim",
    contactOwner: "Michael Chen",
    lastContact: "2025-01-22",
  },
  {
    id: "7",
    name: "James Wilson",
    title: "Engineering Manager",
    department: "Technology",
    seniority: "manager",
    email: "james.wilson@acmecorp.com",
    phone: "+1 (555) 200-0002",
    status: "warm",
    engagementScore: 72,
    role: "technical-evaluator",
    reportsTo: "6",
    linkedIn: "https://linkedin.com/in/jameswilson",
    contactOwner: "Michael Chen",
    lastContact: "2025-01-19",
  },
  {
    id: "8",
    name: "Emily Foster",
    title: "Senior Developer",
    department: "Technology",
    seniority: "senior",
    email: "emily.foster@acmecorp.com",
    phone: "+1 (555) 200-0003",
    status: "engaged",
    engagementScore: 78,
    role: "influencer",
    reportsTo: "7",
    linkedIn: "https://linkedin.com/in/emilyfoster",
    contactOwner: "Michael Chen",
    lastContact: "2025-01-20",
  },
  {
    id: "9",
    name: "Daniel Park",
    title: "Mid Developer",
    department: "Technology",
    seniority: "mid",
    email: "daniel.park@acmecorp.com",
    phone: "+1 (555) 200-0004",
    status: "new",
    engagementScore: 45,
    role: "influencer",
    reportsTo: "7",
    linkedIn: "https://linkedin.com/in/danielpark",
    contactOwner: "Michael Chen",
    lastContact: "2025-01-15",
  },
  {
    id: "10",
    name: "Sophia Martinez",
    title: "Junior Developer",
    department: "Technology",
    seniority: "junior",
    email: "sophia.martinez@acmecorp.com",
    phone: "+1 (555) 200-0005",
    status: "unknown",
    engagementScore: 30,
    reportsTo: "7",
    linkedIn: "https://linkedin.com/in/sophiamartinez",
    contactOwner: "Michael Chen",
    lastContact: "2025-01-10",
  },
  {
    id: "11",
    name: "Michael Roberts",
    title: "QA Lead",
    department: "Technology",
    seniority: "senior",
    email: "michael.roberts@acmecorp.com",
    phone: "+1 (555) 200-0006",
    status: "engaged",
    engagementScore: 80,
    role: "technical-evaluator",
    reportsTo: "6",
    linkedIn: "https://linkedin.com/in/michaelroberts",
    contactOwner: "Michael Chen",
    lastContact: "2025-01-21",
  },
  {
    id: "12",
    name: "Amanda Lee",
    title: "QA Tester",
    department: "Technology",
    seniority: "mid",
    email: "amanda.lee@acmecorp.com",
    phone: "+1 (555) 200-0007",
    status: "warm",
    engagementScore: 65,
    reportsTo: "11",
    linkedIn: "https://linkedin.com/in/amandalee",
    contactOwner: "Michael Chen",
    lastContact: "2025-01-17",
  },
  {
    id: "13",
    name: "Kevin Zhang",
    title: "DevOps Engineer",
    department: "Technology",
    seniority: "senior",
    email: "kevin.zhang@acmecorp.com",
    phone: "+1 (555) 200-0008",
    status: "champion",
    engagementScore: 92,
    role: "champion",
    reportsTo: "6",
    linkedIn: "https://linkedin.com/in/kevinzhang",
    contactOwner: "Michael Chen",
    lastContact: "2025-01-23",
  },
  {
    id: "14",
    name: "Lisa Anderson",
    title: "Solutions Architect",
    department: "Technology",
    seniority: "senior",
    email: "lisa.anderson@acmecorp.com",
    phone: "+1 (555) 200-0009",
    status: "engaged",
    engagementScore: 86,
    role: "technical-evaluator",
    reportsTo: "6",
    linkedIn: "https://linkedin.com/in/lisaanderson",
    contactOwner: "Michael Chen",
    lastContact: "2025-01-22",
  },
  {
    id: "15",
    name: "Christopher Brown",
    title: "IT Support Manager",
    department: "Technology",
    seniority: "manager",
    email: "christopher.brown@acmecorp.com",
    phone: "+1 (555) 200-0010",
    status: "warm",
    engagementScore: 68,
    reportsTo: "4",
    linkedIn: "https://linkedin.com/in/christopherbrown",
    contactOwner: "Sarah Williams",
    lastContact: "2025-01-16",
  },
  {
    id: "16",
    name: "Nicole Taylor",
    title: "IT Support Analyst",
    department: "Technology",
    seniority: "junior",
    email: "nicole.taylor@acmecorp.com",
    phone: "+1 (555) 200-0011",
    status: "new",
    engagementScore: 40,
    reportsTo: "15",
    linkedIn: "https://linkedin.com/in/nicoletaylor",
    contactOwner: "Sarah Williams",
    lastContact: "2025-01-12",
  },

  // Finance
  {
    id: "17",
    name: "Thomas Wright",
    title: "Finance Director",
    department: "Finance",
    seniority: "director",
    email: "thomas.wright@acmecorp.com",
    phone: "+1 (555) 300-0001",
    status: "engaged",
    engagementScore: 83,
    role: "economic-buyer",
    reportsTo: "2",
    linkedIn: "https://linkedin.com/in/thomaswright",
    contactOwner: "Sarah Williams",
    lastContact: "2025-01-21",
  },
  {
    id: "18",
    name: "Patricia Green",
    title: "Senior Accountant",
    department: "Finance",
    seniority: "senior",
    email: "patricia.green@acmecorp.com",
    phone: "+1 (555) 300-0002",
    status: "warm",
    engagementScore: 70,
    reportsTo: "17",
    linkedIn: "https://linkedin.com/in/patriciagreen",
    contactOwner: "Sarah Williams",
    lastContact: "2025-01-18",
  },
  {
    id: "19",
    name: "Brian Mitchell",
    title: "AP/AR Manager",
    department: "Finance",
    seniority: "manager",
    email: "brian.mitchell@acmecorp.com",
    phone: "+1 (555) 300-0003",
    status: "new",
    engagementScore: 48,
    reportsTo: "17",
    linkedIn: "https://linkedin.com/in/brianmitchell",
    contactOwner: "Sarah Williams",
    lastContact: "2025-01-14",
  },

  // Procurement
  {
    id: "20",
    name: "Rebecca Johnson",
    title: "Procurement Director",
    department: "Procurement",
    seniority: "director",
    email: "rebecca.johnson@acmecorp.com",
    phone: "+1 (555) 400-0001",
    status: "blocker",
    engagementScore: 25,
    role: "blocker",
    reportsTo: "2",
    linkedIn: "https://linkedin.com/in/rebeccajohnson",
    contactOwner: "Sarah Williams",
    lastContact: "2025-01-08",
  },
  {
    id: "21",
    name: "Steven Davis",
    title: "Procurement Specialist",
    department: "Procurement",
    seniority: "mid",
    email: "steven.davis@acmecorp.com",
    phone: "+1 (555) 400-0002",
    status: "warm",
    engagementScore: 62,
    reportsTo: "20",
    linkedIn: "https://linkedin.com/in/stevendavis",
    contactOwner: "Sarah Williams",
    lastContact: "2025-01-16",
  },

  // Risk & Compliance
  {
    id: "22",
    name: "Angela White",
    title: "Head of Risk",
    department: "Risk & Compliance",
    seniority: "director",
    email: "angela.white@acmecorp.com",
    phone: "+1 (555) 500-0001",
    status: "engaged",
    engagementScore: 81,
    role: "influencer",
    reportsTo: "2",
    linkedIn: "https://linkedin.com/in/angelawhite",
    contactOwner: "Michael Chen",
    lastContact: "2025-01-20",
  },
  {
    id: "23",
    name: "Gregory Harris",
    title: "Risk Manager",
    department: "Risk & Compliance",
    seniority: "manager",
    email: "gregory.harris@acmecorp.com",
    phone: "+1 (555) 500-0002",
    status: "warm",
    engagementScore: 67,
    reportsTo: "22",
    linkedIn: "https://linkedin.com/in/gregoryharris",
    contactOwner: "Michael Chen",
    lastContact: "2025-01-17",
  },
  {
    id: "24",
    name: "Michelle Clark",
    title: "Compliance Analyst",
    department: "Risk & Compliance",
    seniority: "mid",
    email: "michelle.clark@acmecorp.com",
    phone: "+1 (555) 500-0003",
    status: "new",
    engagementScore: 52,
    reportsTo: "22",
    linkedIn: "https://linkedin.com/in/michelleclark",
    contactOwner: "Michael Chen",
    lastContact: "2025-01-13",
  },

  // Operations
  {
    id: "25",
    name: "Jonathan Lewis",
    title: "Ops Manager",
    department: "Operations",
    seniority: "manager",
    email: "jonathan.lewis@acmecorp.com",
    phone: "+1 (555) 600-0001",
    status: "engaged",
    engagementScore: 77,
    role: "influencer",
    reportsTo: "3",
    linkedIn: "https://linkedin.com/in/jonathanlewis",
    contactOwner: "Sarah Williams",
    lastContact: "2025-01-19",
  },
  {
    id: "26",
    name: "Samantha Hill",
    title: "Ops Analyst",
    department: "Operations",
    seniority: "mid",
    email: "samantha.hill@acmecorp.com",
    phone: "+1 (555) 600-0002",
    status: "warm",
    engagementScore: 63,
    reportsTo: "25",
    linkedIn: "https://linkedin.com/in/samanthahill",
    contactOwner: "Sarah Williams",
    lastContact: "2025-01-15",
  },
  {
    id: "27",
    name: "Andrew Scott",
    title: "Ops Analyst",
    department: "Operations",
    seniority: "junior",
    email: "andrew.scott@acmecorp.com",
    phone: "+1 (555) 600-0003",
    status: "unknown",
    engagementScore: 35,
    reportsTo: "25",
    linkedIn: "https://linkedin.com/in/andrewscott",
    contactOwner: "Sarah Williams",
    lastContact: "2025-01-11",
  },
];

export const mockAccount: Account = {
  id: "acc-1",
  name: "Acme Corp",
  industry: "Enterprise Software",
  size: "5000+ employees",
  contacts: mockContacts,
  lastUpdated: "2025-01-23",
  engagementScore: 72,
};
