import { Account, Contact } from "./types";

export const mockContacts: Contact[] = [
  {
    id: "1",
    name: "Sarah Chen",
    title: "CTO",
    department: "Technology",
    email: "sarah.chen@acmecorp.com",
    status: "champion",
    engagementScore: 95,
    role: "champion",
    lastContact: "2025-01-20",
  },
  {
    id: "2",
    name: "Michael Roberts",
    title: "VP Engineering",
    department: "Technology",
    email: "michael.r@acmecorp.com",
    status: "engaged",
    engagementScore: 82,
    role: "technical-evaluator",
    reportsTo: "1",
    lastContact: "2025-01-18",
  },
  {
    id: "3",
    name: "Jennifer Liu",
    title: "CFO",
    department: "Finance",
    email: "jliu@acmecorp.com",
    status: "warm",
    engagementScore: 65,
    role: "economic-buyer",
    lastContact: "2025-01-10",
  },
  {
    id: "4",
    name: "David Park",
    title: "Finance Manager",
    department: "Finance",
    email: "dpark@acmecorp.com",
    status: "new",
    engagementScore: 45,
    role: "influencer",
    reportsTo: "3",
    lastContact: "2025-01-15",
  },
  {
    id: "5",
    name: "Lisa Thompson",
    title: "CPO",
    department: "Procurement",
    email: "lthompson@acmecorp.com",
    status: "blocker",
    engagementScore: 30,
    role: "blocker",
    lastContact: "2025-01-05",
  },
  {
    id: "6",
    name: "James Wilson",
    title: "Procurement Lead",
    department: "Procurement",
    email: "jwilson@acmecorp.com",
    status: "warm",
    engagementScore: 58,
    role: "influencer",
    reportsTo: "5",
    lastContact: "2025-01-12",
  },
  {
    id: "7",
    name: "Amanda Foster",
    title: "VP Operations",
    department: "Operations",
    email: "afoster@acmecorp.com",
    status: "engaged",
    engagementScore: 78,
    role: "influencer",
    lastContact: "2025-01-19",
  },
];

export const mockAccount: Account = {
  id: "acc-1",
  name: "Acme Corp",
  industry: "Enterprise Software",
  size: "5000+ employees",
  contacts: mockContacts,
  lastUpdated: "2025-01-20",
  engagementScore: 72,
};
