import { Talent, TalentEngagement } from "./types";

export const mockTalents: Talent[] = [
  {
    id: "t1",
    name: "Alex Chen",
    email: "alex.chen@consultant.com",
    phone: "+1 (555) 200-0001",
    phoneNumbers: [
      { value: "+1 (555) 200-0001", label: "Mobile", preferred: true },
    ],
    skills: ["Python", "Data Engineering", "Spark", "AWS", "Airflow"],
    roleType: "Data Engineer",
    seniority: "senior",
    availability: "available",
    rate: "$150/hr",
    notes: "Strong background in financial services data pipelines.",
    aiOverview: "Experienced data engineer with 8+ years in building scalable data pipelines for financial services. Expert in Python, Spark, and AWS data stack. Led migration of legacy ETL to modern cloud-native architecture at major investment bank.",
    linkedIn: "https://linkedin.com/in/alexchen",
    location: "New York, NY",
    lastUpdated: "2025-01-10",
    dataQuality: "parsed",
    status: "active",
    cvSource: "upload",
  },
  {
    id: "t2",
    name: "Maria Santos",
    email: "maria.santos@freelance.io",
    phone: "+1 (555) 200-0002",
    phoneNumbers: [
      { value: "+1 (555) 200-0002", label: "Mobile", preferred: true },
      { value: "+1 (555) 200-0022", label: "Work", preferred: false },
    ],
    skills: ["Business Analysis", "Requirements Gathering", "JIRA", "Agile", "SQL"],
    roleType: "Business Analyst",
    seniority: "mid",
    availability: "interviewing",
    rate: "$95/hr",
    notes: "Currently interviewing with TechStart Inc for Q1 project.",
    aiOverview: "Detail-oriented business analyst with 5 years experience bridging technical and business teams. Strong in requirements documentation, stakeholder management, and agile methodologies. Healthcare and fintech domain expertise.",
    linkedIn: "https://linkedin.com/in/mariasantos",
    location: "Chicago, IL",
    lastUpdated: "2025-01-12",
    dataQuality: "parsed",
    status: "active",
    cvSource: "linkedin",
  },
  {
    id: "t3",
    name: "James Wilson",
    email: "j.wilson@architect.co",
    phone: "+1 (555) 200-0003",
    phoneNumbers: [
      { value: "+1 (555) 200-0003", label: "Mobile", preferred: true },
    ],
    skills: ["Solution Architecture", "AWS", "Azure", "Kubernetes", "Microservices", "Java"],
    roleType: "Solutions Architect",
    seniority: "executive",
    availability: "deployed",
    rate: "$200/hr",
    notes: "Currently deployed at Acme Corp on cloud migration project until Q2.",
    aiOverview: "Enterprise solutions architect with 15+ years designing large-scale distributed systems. Former AWS Principal SA. Led $50M+ cloud transformations for Fortune 500 companies. Expert in microservices, event-driven architecture, and multi-cloud strategies.",
    linkedIn: "https://linkedin.com/in/jameswilson",
    location: "San Francisco, CA",
    lastUpdated: "2025-01-08",
    dataQuality: "parsed",
    status: "active",
    cvSource: "upload",
  },
  {
    id: "t4",
    name: "Priya Sharma",
    email: "priya.sharma@tech.consulting",
    phone: "+1 (555) 200-0004",
    phoneNumbers: [
      { value: "+1 (555) 200-0004", label: "Mobile", preferred: true },
    ],
    skills: ["React", "TypeScript", "Node.js", "GraphQL", "PostgreSQL"],
    roleType: "Full Stack Developer",
    seniority: "senior",
    availability: "available",
    rate: "$130/hr",
    notes: "Excellent frontend skills, available for immediate start.",
    aiOverview: "Full stack developer specializing in React and Node.js with 6 years of experience. Strong advocate for TypeScript and modern web standards. Built multiple production apps serving 100k+ users.",
    linkedIn: "https://linkedin.com/in/priyasharma",
    location: "Austin, TX",
    lastUpdated: "2025-01-15",
    dataQuality: "needs-review",
    status: "new",
    cvSource: "image",
  },
  {
    id: "t5",
    name: "Michael Brown",
    email: "m.brown@dataops.io",
    phone: "+1 (555) 200-0005",
    phoneNumbers: [
      { value: "+1 (555) 200-0005", label: "Work", preferred: true },
      { value: "+1 (555) 200-0055", label: "Mobile", preferred: false },
    ],
    skills: ["Power BI", "Tableau", "SQL", "Python", "Data Visualization"],
    roleType: "Data Analyst",
    seniority: "mid",
    availability: "available",
    rate: "$85/hr",
    notes: "Strong visualization skills, banking domain experience.",
    aiOverview: "Data analyst with expertise in business intelligence and visualization tools. 4 years experience in banking sector creating executive dashboards and automated reporting solutions. Proficient in SQL, Python, and BI platforms.",
    linkedIn: "https://linkedin.com/in/michaelbrown",
    location: "Boston, MA",
    lastUpdated: "2025-01-11",
    dataQuality: "parsed",
    status: "active",
    cvSource: "manual",
  },
  {
    id: "t6",
    name: "Sarah Kim",
    email: "sarah.kim@pmconsult.com",
    phone: "+1 (555) 200-0006",
    phoneNumbers: [
      { value: "+1 (555) 200-0006", label: "Mobile", preferred: true },
    ],
    skills: ["Project Management", "Agile", "Scrum", "JIRA", "Confluence", "PMP"],
    roleType: "Project Manager",
    seniority: "manager",
    availability: "interviewing",
    rate: "$120/hr",
    notes: "PMP certified, strong in agile transformations.",
    aiOverview: "PMP-certified project manager with 7 years leading technology initiatives. Specialist in agile transformations and cross-functional team leadership. Successfully delivered 20+ projects ranging from $500K to $5M in budget.",
    linkedIn: "https://linkedin.com/in/sarahkim",
    location: "Seattle, WA",
    lastUpdated: "2025-01-13",
    dataQuality: "parsed",
    status: "active",
    cvSource: "upload",
  },
  {
    id: "t7",
    name: "David Lee",
    email: "david.lee@security.expert",
    phone: "+1 (555) 200-0007",
    phoneNumbers: [
      { value: "+1 (555) 200-0007", label: "Mobile", preferred: true },
    ],
    skills: ["Cybersecurity", "Penetration Testing", "SIEM", "SOC", "CISSP"],
    roleType: "Security Consultant",
    seniority: "senior",
    availability: "deployed",
    rate: "$175/hr",
    notes: "Currently on long-term engagement with Global Solutions.",
    aiOverview: "CISSP-certified security consultant with 10+ years in cybersecurity. Former government contractor specializing in penetration testing and security assessments. Built and led SOC teams for multiple enterprises.",
    linkedIn: "https://linkedin.com/in/davidlee",
    location: "Washington, DC",
    lastUpdated: "2025-01-05",
    dataQuality: "parsed",
    status: "active",
    cvSource: "linkedin",
  },
  {
    id: "t8",
    name: "Emma Johnson",
    email: "emma.j@cloudops.net",
    phone: "+1 (555) 200-0008",
    phoneNumbers: [
      { value: "+1 (555) 200-0008", label: "Mobile", preferred: true },
    ],
    skills: ["DevOps", "Terraform", "Docker", "CI/CD", "Jenkins", "GitLab"],
    roleType: "DevOps Engineer",
    seniority: "senior",
    availability: "available",
    rate: "$140/hr",
    notes: "Expert in infrastructure as code, available immediately.",
    aiOverview: "DevOps engineer with deep expertise in infrastructure automation and CI/CD pipelines. 6 years experience implementing GitOps practices and containerization strategies. Terraform and Kubernetes specialist.",
    linkedIn: "https://linkedin.com/in/emmajohnson",
    location: "Denver, CO",
    lastUpdated: "2025-01-14",
    dataQuality: "needs-review",
    status: "active",
    cvSource: "image",
  },
  {
    id: "t9",
    name: "Robert Garcia",
    email: "r.garcia@ml.consulting",
    phone: "+1 (555) 200-0009",
    phoneNumbers: [
      { value: "+1 (555) 200-0009", label: "Mobile", preferred: true },
    ],
    skills: ["Machine Learning", "Python", "TensorFlow", "PyTorch", "NLP", "Computer Vision"],
    roleType: "ML Engineer",
    seniority: "senior",
    availability: "available",
    rate: "$180/hr",
    notes: "PhD in Computer Science, specialized in NLP applications.",
    aiOverview: "PhD in Computer Science with focus on NLP and computer vision. 5 years industry experience building production ML systems. Published researcher with expertise in transformer architectures and MLOps best practices.",
    linkedIn: "https://linkedin.com/in/robertgarcia",
    location: "Palo Alto, CA",
    lastUpdated: "2025-01-09",
    dataQuality: "parsed",
    status: "active",
    cvSource: "upload",
  },
  {
    id: "t10",
    name: "Lisa Wang",
    email: "lisa.wang@uxdesign.co",
    phone: "+1 (555) 200-0010",
    phoneNumbers: [
      { value: "+1 (555) 200-0010", label: "Mobile", preferred: true },
    ],
    skills: ["UX Design", "Figma", "User Research", "Prototyping", "Design Systems"],
    roleType: "UX Designer",
    seniority: "mid",
    availability: "interviewing",
    rate: "$100/hr",
    notes: "Strong portfolio in fintech and healthcare applications.",
    aiOverview: "UX designer with 4 years creating intuitive digital experiences in fintech and healthcare. Expert in Figma, user research, and design systems. Portfolio includes award-winning mobile apps and enterprise dashboards.",
    linkedIn: "https://linkedin.com/in/lisawang",
    location: "Los Angeles, CA",
    lastUpdated: "2025-01-16",
    dataQuality: "parsed",
    status: "on-hold",
    cvSource: "manual",
  },
];

export const roleTypeOptions = [
  "Data Engineer",
  "Business Analyst",
  "Solutions Architect",
  "Enterprise Architect",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "Data Analyst",
  "Project Manager",
  "Product Manager",
  "Security Consultant",
  "DevOps Engineer",
  "ML Engineer",
  "Data Scientist",
  "UX Designer",
  "QA Engineer",
  "Scrum Master",
  "Technical Writer",
];

export const skillOptions = [
  "Python",
  "JavaScript",
  "TypeScript",
  "React",
  "Node.js",
  "Java",
  "SQL",
  "AWS",
  "Azure",
  "GCP",
  "Kubernetes",
  "Docker",
  "Terraform",
  "Data Engineering",
  "Machine Learning",
  "Business Analysis",
  "Project Management",
  "Agile",
  "Scrum",
  "Power BI",
  "Tableau",
  "Figma",
  "Cybersecurity",
];

// Mock engagements linking talents to companies
export const mockEngagements: TalentEngagement[] = [
  {
    id: "eng-1",
    talentId: "t3", // James Wilson - Solutions Architect
    companyId: "acc-1", // Acme Corp
    status: "deployed",
    roleType: "Solutions Architect",
    department: "Technology",
    startDate: "2024-11-01",
    endDate: "2025-03-31",
    notes: "Leading cloud migration initiative",
  },
  {
    id: "eng-2",
    talentId: "t2", // Maria Santos - Business Analyst
    companyId: "acc-1", // Acme Corp
    status: "interviewing",
    roleType: "Business Analyst",
    department: "Product",
    notes: "Final round scheduled for next week",
  },
  {
    id: "eng-3",
    talentId: "t1", // Alex Chen - Data Engineer
    companyId: "acc-1", // Acme Corp
    status: "proposed",
    roleType: "Data Engineer",
    department: "Technology",
    notes: "Proposed for Q2 data pipeline project",
  },
  {
    id: "eng-4",
    talentId: "t7", // David Lee - Security Consultant
    companyId: "acc-3", // Global Solutions
    status: "deployed",
    roleType: "Security Consultant",
    department: "Technology",
    startDate: "2024-10-15",
    notes: "Long-term security assessment engagement",
  },
  {
    id: "eng-5",
    talentId: "t4", // Priya Sharma - Full Stack Developer
    companyId: "acc-2", // TechStart Inc
    status: "proposed",
    roleType: "Full Stack Developer",
    department: "Engineering",
    notes: "Proposed for product rebuild project",
  },
  {
    id: "eng-6",
    talentId: "t8", // Emma Johnson - DevOps Engineer
    companyId: "acc-1", // Acme Corp
    status: "proposed",
    roleType: "DevOps Engineer",
    department: "Technology",
    notes: "Proposed to support cloud migration team",
  },
];
